# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
CitiesWeather = pd.read_csv('CleanedUpcitiesweather.csv')

CitiesWeather.dropna(inplace = True)
CitiesWeather.head()

,Unnamed: 0,City,Country,Latitude,Longitude,Clouduness (Percent),Wind Speed,Humidity,Temperature fahrenhiet,Converted Date
0,0,Rikitea,PF,-23.12,-134.97,58,1.92,69,75.614,2020-05-10
1,1,Jalor,IN,25.35,72.62,0,3.46,52,85.856,2020-05-10
2,2,Mataura,NZ,-46.19,168.86,60,0.91,65,61.304,2020-05-10
3,3,Bredasdorp,ZA,-34.53,20.04,0,2.10,93,53.600,2020-05-10
4,4,Tasiilaq,GL,65.61,-37.64,18,7.20,87,32.000,2020-05-10

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
# Store latitude and longitude in locations
locations = CitiesWeather[["Latitude", "Longitude"]]

# Fill NaN values and convert to float
Humidity = CitiesWeather["Humidity"].astype(float)

In [6]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=Humidity, 
                                 dissipating=False, max_intensity=200,
                                 point_radius=5)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
Temp1 = CitiesWeather.loc[CitiesWeather["Temperature fahrenhiet"]>= 70]
Temp1
Temp2 = Temp1.loc[Temp1["Temperature fahrenhiet"]<= 80]
Temp2
Wind = Temp2.loc[Temp2["Wind Speed"]<= 10]
Wind
Clouduness = Wind.loc[Wind["Clouduness (Percent)"]== 0]
Clouduness

,Unnamed: 0,City,Country,Latitude,Longitude,Clouduness (Percent),Wind Speed,Humidity,Temperature fahrenhiet,Converted Date
59,59,La Providencia,MX,28.72,-111.58,0,2.24,77,75.668,2020-05-10
61,61,Arraial do Cabo,BR,-22.97,-42.03,0,5.47,69,70.754,2020-05-10
64,64,Abéché,TD,13.83,20.83,0,4.78,14,77.072,2020-05-10
147,147,Birin,NP,26.89,88.07,0,1.90,39,74.516,2020-05-10
215,215,Poum,NC,-20.23,164.02,0,2.58,67,76.460,2020-05-10
216,216,Kidal,ML,18.44,1.41,0,0.16,15,77.450,2020-05-10
257,257,San Patricio,MX,19.22,-104.70,0,2.03,78,74.696,2020-05-10
280,280,Coahuayana Viejo,MX,18.73,-103.68,0,0.10,83,75.578,2020-05-10
313,313,Sena Madureira,BR,-9.07,-68.66,0,0.18,79,71.114,2020-05-10
316,316,Turkmenabat,TM,39.07,63.58,0,4.10,49,73.400,2020-05-10
364,364,Ariquemes,BR,-9.91,-63.04,0,0.69,91,72.806,2020-05-10
372,372,Linqing,CN,36.85,115.71,0,3.26,36,76.280,2020-05-10
378,378,Sawtell,AU,-30.38,153.10,0,5.10,60,72.680,2020-05-10
440,440,Perth,AU,-31.93,115.83,0,4.60,35,70.124,2020-05-10
462,462,Guerrero,MX,17.67,-100.00,0,2.47,55,73.598,2020-05-10
469,469,Tyukalinsk,RU,55.87,72.20,0,4.95,43,70.088,2020-05-10
497,497,Chardara,KZ,41.25,67.97,0,3.54,53,72.374,2020-05-10

In [8]:
#My personal vacation criteria 
Temp3 = CitiesWeather.loc[CitiesWeather["Temperature fahrenhiet"]>= 80]

Temp4 = Temp3.loc[Temp3["Temperature fahrenhiet"]<= 85]

Wind2 = Temp4.loc[Temp4["Wind Speed"]<= 10]

SarasVacationSpots = Wind2.loc[Wind2["Clouduness (Percent)"]== 0]
SarasVacationSpots.to_csv("SarasVacationSpots.csv")

# Visualize to confirm airport data appears
SarasVacationSpots.head(15)

,Unnamed: 0,City,Country,Latitude,Longitude,Clouduness (Percent),Wind Speed,Humidity,Temperature fahrenhiet,Converted Date
32,32,Mount Isa,AU,-20.73,139.50,0,6.70,20,82.400,2020-05-10
58,58,Waingapu,ID,-9.66,120.26,0,6.62,67,84.632,2020-05-10
80,80,Mackay,AU,-21.15,149.20,0,4.10,65,80.474,2020-05-10
272,272,Araouane,ML,18.90,-3.53,0,1.23,14,83.480,2020-05-10
363,363,Cockburn Town,TC,21.46,-71.14,0,7.52,85,80.852,2020-05-10
549,549,Pochutla,MX,15.74,-96.47,0,1.16,76,84.992,2020-05-10

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [9]:
hotel_df = SarasVacationSpots
hotel_df['Hotel Name'] = ""
#hotel_df['Hotel Address'] = ""
#hotel_df['Hotel Rating'] = ""

hotel_df.head()

params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}

# Use the lat/lng we recovered to identify airports
for index, row in SarasVacationSpots.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))
    #pprint(name_address)
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address['results'][0]["name"]
        #hotel_df.loc[index, "Hotel Address"] = name_address["results"][0]["name"]
        #hotel_df.loc[index, "Hotel Rating"] = name_address["results"][0]["rating"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
hotel_df.head(10)

C:\Users\sarar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sarar\Anaconda3\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.

,Unnamed: 0,City,Country,Latitude,Longitude,Clouduness (Percent),Wind Speed,Humidity,Temperature fahrenhiet,Converted Date,Hotel Name
32,32,Mount Isa,AU,-20.73,139.50,0,6.70,20,82.400,2020-05-10,Abacus Motel
58,58,Waingapu,ID,-9.66,120.26,0,6.62,67,84.632,2020-05-10,Hotel Jemmy
80,80,Mackay,AU,-21.15,149.20,0,4.10,65,80.474,2020-05-10,Ocean International Hotel
272,272,Araouane,ML,18.90,-3.53,0,1.23,14,83.480,2020-05-10,
363,363,Cockburn Town,TC,21.46,-71.14,0,7.52,85,80.852,2020-05-10,Osprey Beach Hotel
549,549,Pochutla,MX,15.74,-96.47,0,1.16,76,84.992,2020-05-10,Hotel Alebrijes

In [11]:
hotel_df.to_csv("Hotels.csv")

# Visualize to confirm airport data appears
hotel_df.head(10)

,Unnamed: 0,City,Country,Latitude,Longitude,Clouduness (Percent),Wind Speed,Humidity,Temperature fahrenhiet,Converted Date,Hotel Name
32,32,Mount Isa,AU,-20.73,139.50,0,6.70,20,82.400,2020-05-10,Abacus Motel
58,58,Waingapu,ID,-9.66,120.26,0,6.62,67,84.632,2020-05-10,Hotel Jemmy
80,80,Mackay,AU,-21.15,149.20,0,4.10,65,80.474,2020-05-10,Ocean International Hotel
272,272,Araouane,ML,18.90,-3.53,0,1.23,14,83.480,2020-05-10,
363,363,Cockburn Town,TC,21.46,-71.14,0,7.52,85,80.852,2020-05-10,Osprey Beach Hotel
549,549,Pochutla,MX,15.74,-96.47,0,1.16,76,84.992,2020-05-10,Hotel Alebrijes

In [12]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [13]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))